version: '3.8'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - mynetwork
  front:
    build: ./frontend
    networks:
      -mynetwork 
  back:
    build: ./backend
    networks:
     -mynetwork



networks:
  -mynetwork:
